### ISSUE TITLE
Broken doc links

### ISSUE THREAD

**Issue by anisse** [ferrilab/bitvec#202]
The "memory layout" link in https://docs.rs/bitvec/latest/bitvec/array/struct.BitArray.html#method.align_to is broken, it points to:
https://bitvecto-rs.github.io/bitvec/memory-layout.html

In docs.rs, the "Homepage" link points to https://bitvecto-rs.github.io/bitvec/

**Comment by jam1garner** [comment]
Similarly https://docs.rs/bitvec/latest/bitvec/order/struct.Lsb0.html#least-significant-first-bit-traversal points to https://bitvecto-rs.github.io/bitvec/memory-representation

**Comment by myrrlyn** [comment]
Hi! I apologize for the long delay; I have had a *very* stressful winter and have not had the time or energy to check this repository in a timely manner. I'm trying to catch up now.

I've been doing some overhaul of the documentation and user manual, in addition to (now two) relocation events on GitHub. Stray errors like this have been, unfortunately, inevitable. I try to read my entire documentation set, including following links, as I go through it, but I've accumulated so much familiarity blindness that it gets harder and harder to spot errors like this myself.

These are fixed on `main`, and will be updated next time I actually fulfill my promise to do cut a release. I apologize again for the long wait.
